package com.cleanlearn.util;

public class EmailContent {

    public static final String DEADLINE_MISSED_EMAIL_TEMPLATE = """
        <!DOCTYPE html>
            <html lang="en">
            <head>
                <meta charset="UTF-8">
                <meta name="viewport" content="width=device-width, initial-scale=1.0">
                <title>Task Deadline Reminder</title>
            </head>
            <body style="margin:0; padding:0; font-family: Arial, Helvetica, sans-serif; background-color:#f4f4f4;">

                <table width="100%" cellpadding="0" cellspacing="0" style="background-color:#f4f4f4; padding:30px 0;">
                    <tr>
                        <td align="center">

                            <table width="600" cellpadding="0" cellspacing="0"
                                style="background-color:#ffffff; border-radius:8px; overflow:hidden;">

                                <tr>
                                    <td style="background-color:#d9534f; color:#ffffff; padding:20px; text-align:center;">
                                        <h2 style="margin:0;">⚠️ Deadline Missed</h2>
                                    </td>
                                </tr>

                                <tr>
                                    <td style="padding:30px; color:#333333;">

                                        <p>Hello,</p>

                                        <p>
                                            This is a reminder that one or more of your scheduled tasks
                                            have passed their expected completion date and are still marked as pending.
                                        </p>

                                        <p>
                                            Timely completion helps maintain your learning momentum and
                                            ensures that important review activities are not delayed.
                                        </p>

                                        <div style="
                                            background-color:#fff3cd;
                                            border-left:4px solid #ffc107;
                                            padding:15px;
                                            margin:20px 0;">
                                            <strong>Action Required:</strong><br>
                                            Please review the pending items and complete them as soon as possible.
                                        </div>

                                        <p>
                                            If you have already completed the task, please update its status accordingly.
                                        </p>

                                        <p>
                                            Thank you for your attention.
                                        </p>

                                        <p>
                                            Regards,<br>
                                            <strong>CleanLearn Reminder Service</strong>
                                        </p>

                                    </td>
                                </tr>

                                <tr>
                                    <td style="
                                        background-color:#f8f9fa;
                                        color:#777777;
                                        text-align:center;
                                        padding:15px;
                                        font-size:12px;">
                                        This is an automated reminder generated by CleanLearn.
                                    </td>
                                </tr>

                            </table>

                        </td>
                    </tr>
                </table>

            </body>
            </html>

    """;

    public static final String STUDY_PLAN_EMAIL_TEMPLATE = """
            <!DOCTYPE html>
            <html lang="en">
            <head>
                <meta charset="UTF-8">
                <style>
                    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Arial, sans-serif; background-color: #f4f7f6; margin: 0; padding: 20px; color: #333333; line-height: 1.6; }
                    .container { max-width: 600px; margin: 0 auto; background: #ffffff; padding: 30px; border-radius: 10px; box-shadow: 0 4px 15px rgba(0,0,0,0.05); }
                    h1, h2, h3 { color: #2c3e50; }
                    .header { text-align: center; border-bottom: 2px solid #edf2f7; padding-bottom: 20px; margin-bottom: 25px; }
                    .header h1 { margin: 0; color: #2b6cb0; font-size: 24px; }
                    .section-card { background: #ebf8fa; padding: 20px; border-radius: 8px; margin-bottom: 25px; }
                    .section-card h2 { margin-top: 0; color: #2b6cb0; font-size: 18px; }
                    
                    /* Styling for the Pending Revisions Section */
                    .revision-card { background: #fdf6e3; padding: 20px; border-radius: 8px; border-left: 4px solid #d97706; margin-bottom: 25px; }
                    .revision-card h2 { margin-top: 0; color: #b45309; font-size: 18px; }
                    
                    .problem-card { border: 1px solid #e2e8f0; padding: 20px; margin-bottom: 15px; border-radius: 8px; border-left: 4px solid #4299e1; background: #fafafa; }
                    .problem-card h3 { margin-top: 0; font-size: 18px; margin-bottom: 10px; }
                    .badge { display: inline-block; padding: 4px 10px; font-size: 12px; font-weight: 600; border-radius: 15px; background: #edf2f7; color: #4a5568; margin-right: 5px; margin-bottom: 5px; }
                    .badge-difficulty { background: #f6ad55; color: white; }
                    .alert-card { background: #fff5f5; padding: 20px; border-radius: 8px; border-left: 4px solid #f56565; margin-bottom: 25px; }
                    .alert-card h2 { margin-top: 0; color: #c53030; font-size: 18px; }
                    .list-unstyled { padding-left: 20px; margin-top: 10px; }
                    .list-unstyled li { margin-bottom: 8px; }
                    .footer { text-align: center; margin-top: 30px; font-size: 13px; color: #718096; border-top: 1px solid #edf2f7; padding-top: 20px; }
                    p { margin: 8px 0; }
                </style>
            </head>
            <body>
                <div class="container">
                    <div class="header">
                        <h1>🚀 Your Daily Study Plan</h1>
                        <p style="color: #718096; margin: 5px 0 0 0;">Ready to crush your interview prep today?</p>
                    </div>

                    <div class="section-card">
                        <h2>🎯 Today's Focus (%d mins)</h2>
                        <p><strong>Primary Goal:</strong> %s</p>
                        <p><strong>Secondary Goal:</strong> %s</p>
                        <p><strong>Strategy:</strong> %s</p>
                    </div>

                    <div class="revision-card">
                        <h2>🔄 Pending Revisions Today</h2>
                        %s
                    </div>

                    <div>
                        <h2>💻 Recommended Problems</h2>
                        %s
                    </div>

                    <div>
                        <h2>🧠 Learning Strategy</h2>
                        <p><strong>Why these patterns:</strong></p>
                        <ul class="list-unstyled">
                            %s
                        </ul>
                    </div>

                    <div class="alert-card">
                        <h2>🚫 What to Avoid Today</h2>
                        <p><strong>Skip these topics:</strong> %s</p>
                        <p><strong>Reason:</strong> %s</p>
                    </div>

                    <div>
                        <h2>💡 Mentor Observations</h2>
                        <ul class="list-unstyled">
                            %s
                        </ul>
                    </div>

                    <div class="footer">
                        <p>Happy Coding! Keep up the momentum.</p>
                        <p>© CleanLearn Platform</p>
                    </div>
                </div>
            </body>
            </html>
        """;

}